---
title: ""
author: "Jodie Lord"
date: "06/10/2019"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




## Learning Material

_______________________________________________________________________


#### [Python workshop materials and solutions](https://github.com/jodielord/python_teaching_material) 
- Material and solutions across 4 introductory Python workshops. Intended for complete beginners. Topics covered include:
  - [Object assignment](https://github.com/jodielord/python_teaching_material/blob/master/Session1/session1.ipynb)
  - [Basic arithmetic](https://github.com/jodielord/python_teaching_material/blob/master/Session1/session1.ipynb) 
  - [Core data types](https://github.com/jodielord/python_teaching_material/blob/master/Session1/session1.ipynb) 
  - [Slicing](https://github.com/jodielord/python_teaching_material/blob/master/Session1/session1.ipynb) 
  - [Loops](https://github.com/jodielord/python_teaching_material/blob/master/Session2/Session2.ipynb)  
  - [Libraries](https://github.com/jodielord/python_teaching_material/blob/master/Session2/Session2.ipynb) 
  - [Pandas](https://github.com/jodielord/python_teaching_material/blob/master/Session2/Session2.ipynb) 🐼
  - [Data mining](https://github.com/jodielord/python_teaching_material/blob/master/Session2/Session2.ipynb)
  - [Data merging](https://github.com/jodielord/python_teaching_material/blob/master/Session2/Session2.ipynb) 
  - [Basic statistics](https://github.com/jodielord/python_teaching_material/blob/master/Session3/Session3.ipynb) 
  - [Charting](https://github.com/jodielord/python_teaching_material/blob/master/Session3/Session3.ipynb) 
  - [Introduction to machine learning](https://github.com/jodielord/python_teaching_material/blob/master/Session4_Solutions/Session4_Solutions.ipynb) 
  - [Extra Resources and FAQs](https://jodielord.netlify.com/python_workshop_faqs.pdf)
<br>
<br>
<br>

## Introductory primers

_______________________________________________________________________

- [Introduction to R and RStudio.](https://jodielord.netlify.com/Intro_R.pdf)
  - What is R/RStudio?
  - How do I access and navigate RStudio?
  - Basic functionality
  - Useful resources
<br/>
<br/>

- [Introduction to Omics.](https://jodielord.netlify.com/Introduction_to_omics.pdf)
  - Intro to high dimensional data (HDD).
  - What 'omics' is and where it fits into the realms of HDD.
  - Possibilities and challenges.
<br/>
<br/>

- [Introduction to genetics, genomics and genome-wide association studies.](https://jodielord.netlify.com/Introduction_genetics_genomics_GWAS.pdf)
  - Basics of genetics and "complex" disorders.
  - Importance of the Human Genome Project.
  - Basic genome-wide methodology: introduction to GWAS.
  - Importance of genomics in the wider "omics" field.
<br/>
<br/>

- [Going further: Introduction to polygenic scoring.](https://jodielord.netlify.com/Going_further_intro_PRS.pdf)
  - Multiple testing challenges facing GWAS approaches.
  - Polygenic scoring and how this can provide additional insights to standard GWAS outputs.
  - Within-trait vs cross-trait approaches.
  - Working example.


<br/>
<br/>

____________

<br/>
